### ISSUE TITLE
Ayna

### ISSUE THREAD

**Issue by uok825** [gokssu/SmartMirror#1]
Aynı proje üzerine bende zero w ile çalışıyorum. Her şeyi tamamladım ve zero gibi küçük bir bilgisayara yapmayı başardım. Ayrıca PIR sensör ve Röle kartı ile de elektrik tasarrufu ediyorum. Merak ettiğim konu senin ayna için ne kullandığın ve nereden temin ettiğim. Başarılarının devamını dilerim.

- Utku

**Comment by gokssu** [comment]
Ben raspberry pi A+ modelini kullandım ve robotistandan aldım.16 gb lık bir SD kart kullandım. Android bir güç adaptörüyle enerji alıyor onun dışında ekrana HDMI kablosuyla bağlı. Ekranın ayrı bir güç kablosuda var tabi karttan güç çekmiyor. Bir de eski bir mouse'umuda karta taktım. SSH uzaktan bağlantısına gerek duymadan mouse ve ekran klavyesiyle kullanıyorum işletim sistemini. Başka merak ettiğin şeyler varsa Readme yi düzenlicem ordan da öğrenebilirsin. Teşekkür ederim sizede başarılar.

**Comment by gokssu** [comment]
> Aynı proje üzerine bende zero w ile çalışıyorum. Her şeyi tamamladım ve zero gibi küçük bir bilgisayara yapmayı başardım. Ayrıca PIR sensör ve Röle kartı ile de elektrik tasarrufu ediyorum. Merak ettiğim konu senin ayna için ne kullandığın ve nereden temin ettiğim. Başarılarının devamını dilerim.
> 
> * Utku

Ben raspberry pi A+ modelini kullandım ve robotistandan aldım.16 gb lık bir SD kart kullandım. Android bir güç adaptörüyle enerji alıyor onun dışında ekrana HDMI kablosuyla bağlı. Ekranın ayrı bir güç kablosuda var tabi karttan güç çekmiyor. Bir de eski bir mouse'umuda karta taktım. SSH uzaktan bağlantısına gerek duymadan mouse ve ekran klavyesiyle kullanıyorum işletim sistemini. Başka merak ettiğin şeyler varsa Readme yi düzenlicem ordan da öğrenebilirsin. Teşekkür ederim sizede başarılar.

**Comment by uok825** [comment]
> > Aynı proje üzerine bende zero w ile çalışıyorum. Her şeyi tamamladım ve zero gibi küçük bir bilgisayara yapmayı başardım. Ayrıca PIR sensör ve Röle kartı ile de elektrik tasarrufu ediyorum. Merak ettiğim konu senin ayna için ne kullandığın ve nereden temin ettiğim. Başarılarının devamını dilerim.
> > 
> > * Utku
> 
> Ben raspberry pi A+ modelini kullandım ve robotistandan aldım.16 gb lık bir SD kart kullandım. Android bir güç adaptörüyle enerji alıyor onun dışında ekrana HDMI kablosuyla bağlı. Ekranın ayrı bir güç kablosuda var tabi karttan güç çekmiyor. Bir de eski bir mouse'umuda karta taktım. SSH uzaktan bağlantısına gerek duymadan mouse ve ekran klavyesiyle kullanıyorum işletim sistemini. Başka merak ettiğin şeyler varsa Readme yi düzenlicem ordan da öğrenebilirsin. Teşekkür ederim sizede başarılar.

Küçük bir yanlış anlaşılma olmuş, projenin ayna olmasından ötürü, gereksinimleri biliyorum ayrıca teşekkür ederim. Aynaya ne kullandığını sorarken kast ettiğim cam olan ayna da ne kullandığın reflekte cam vs. Iyi akşamlar

- Utku

**Comment by gokssu** [comment]
> > > Aynı proje üzerine bende zero w ile çalışıyorum. Her şeyi tamamladım ve zero gibi küçük bir bilgisayara yapmayı başardım. Ayrıca PIR sensör ve Röle kartı ile de elektrik tasarrufu ediyorum. Merak ettiğim konu senin ayna için ne kullandığın ve nereden temin ettiğim. Başarılarının devamını dilerim.
> > > 
> > > * Utku
> > 
> > 
> > Ben raspberry pi A+ modelini kullandım ve robotistandan aldım.16 gb lık bir SD kart kullandım. Android bir güç adaptörüyle enerji alıyor onun dışında ekrana HDMI kablosuyla bağlı. Ekranın ayrı bir güç kablosuda var tabi karttan güç çekmiyor. Bir de eski bir mouse'umuda karta taktım. SSH uzaktan bağlantısına gerek duymadan mouse ve ekran klavyesiyle kullanıyorum işletim sistemini. Başka merak ettiğin şeyler varsa Readme yi düzenlicem ordan da öğrenebilirsin. Teşekkür ederim sizede başarılar.
> 
> Küçük bir yanlış anlaşılma olmuş, projenin ayna olmasından ötürü, gereksinimleri biliyorum ayrıca teşekkür ederim. Aynaya ne kullandığını sorarken kast ettiğim cam olan ayna da ne kullandığın reflekte cam vs. Iyi akşamlar
> 
> * Utku



Aaa pardon ayna deyince genel düşündüm. Normal bir cam çerçeve yaptırdık monitörün boyutlarına göre arkası olmayan onun üstüne gümüş aynalı cam filtresi yapıştırdık. Arkasındanda ekranın üstünde kalan boşluğu kapatmak için siyah cam filtresi yapıştırdım üst kısımda arkayı göstermemesi için. Çerçeveyi hamur yapıştırıcıyla monitöre yapıştırıp arkasından bantlarlada sabitledim. (Filtreleri otosanayiden aldık araba camlarına yapıştırılıyormuş)

![WhatsApp Image 2020-06-29 at 14 37 02](https://user-images.githubusercontent.com/26454080/86828057-6a0e3000-c09b-11ea-83bc-1bb9da90c880.jpeg)
![WhatsApp Image 2020-06-29 at 14 37 37](https://user-images.githubusercontent.com/26454080/86828060-6aa6c680-c09b-11ea-9767-01d1e9b5ac61.jpeg)
![WhatsApp Image 2020-06-29 at 14 11 37](https://user-images.githubusercontent.com/26454080/86828825-629b5680-c09c-11ea-8ef5-90edef28d414.jpeg)

**Comment by uok825** [comment]
> > > > Aynı proje üzerine bende zero w ile çalışıyorum. Her şeyi tamamladım ve zero gibi küçük bir bilgisayara yapmayı başardım. Ayrıca PIR sensör ve Röle kartı ile de elektrik tasarrufu ediyorum. Merak ettiğim konu senin ayna için ne kullandığın ve nereden temin ettiğim. Başarılarının devamını dilerim.
> > > > 
> > > > * Utku
> > > 
> > > 
> > > Ben raspberry pi A+ modelini kullandım ve robotistandan aldım.16 gb lık bir SD kart kullandım. Android bir güç adaptörüyle enerji alıyor onun dışında ekrana HDMI kablosuyla bağlı. Ekranın ayrı bir güç kablosuda var tabi karttan güç çekmiyor. Bir de eski bir mouse'umuda karta taktım. SSH uzaktan bağlantısına gerek duymadan mouse ve ekran klavyesiyle kullanıyorum işletim sistemini. Başka merak ettiğin şeyler varsa Readme yi düzenlicem ordan da öğrenebilirsin. Teşekkür ederim sizede başarılar.
> > 
> > 
> > Küçük bir yanlış anlaşılma olmuş, projenin ayna olmasından ötürü, gereksinimleri biliyorum ayrıca teşekkür ederim. Aynaya ne kullandığını sorarken kast ettiğim cam olan ayna da ne kullandığın reflekte cam vs. Iyi akşamlar
> > 
> > * Utku
> 
> Aaa pardon ayna deyince genel düşündüm. Normal bir cam çerçeve yaptırdık monitörün boyutlarına göre arkası olmayan onun üstüne gümüş aynalı cam filtresi yapıştırdık. Arkasındanda ekranın üstünde kalan boşluğu kapatmak için siyah cam filtresi yapıştırdım üst kısımda arkayı göstermemesi için. Çerçeveyi hamur yapıştırıcıyla monitöre yapıştırıp arkasından bantlarlada sabitledim. (Filtreleri otosanayiden aldık araba camlarına yapıştırılıyormuş)
> 
> ![WhatsApp Image 2020-06-29 at 14 37 02](https://user-images.githubusercontent.com/26454080/86828057-6a0e3000-c09b-11ea-83bc-1bb9da90c880.jpeg)
> ![WhatsApp Image 2020-06-29 at 14 37 37](https://user-images.githubusercontent.com/26454080/86828060-6aa6c680-c09b-11ea-9767-01d1e9b5ac61.jpeg)
> ![WhatsApp Image 2020-06-29 at 14 11 37](https://user-images.githubusercontent.com/26454080/86828825-629b5680-c09c-11ea-8ef5-90edef28d414.jpeg)

Yanıtın için çok teşekkür ederim. Çok yardımcı oldun, iyi akşamlar dilerim.
